#############################################################################
# Makefile for building: browser
# Generated by qmake (3.1) (Qt 6.0.0)
# Project:  browser.pro
# Template: app
# Command: /opt/qt5/bin/qmake -o Makefile browser.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/opt/qt5/include -I/opt/qt5/include/QtWebEngineWidgets -I/opt/qt5/include/QtWebEngineCore -I/opt/qt5/include/QtQuick -I/opt/qt5/include/QtPrintSupport -I/opt/qt5/include/QtWidgets -I/opt/qt5/include/QtGui -I/opt/qt5/include/QtQmlModels -I/opt/qt5/include/QtQml -I/opt/qt5/include/QtNetwork -I/opt/qt5/include/QtCore -I. -isystem /usr/include/libdrm -I/opt/qt5/mkspecs/linux-g++
QMAKE         = /opt/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = browser1.0.0
DISTDIR = /media/sda3/root/c/browser/.tmp/browser1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/opt/qt5/lib
LIBS          = $(SUBLIBS) /opt/qt5/lib/libQt6WebEngineWidgets.so /opt/qt5/lib/libQt6WebEngineCore.so /opt/qt5/lib/libQt6Quick.so /opt/qt5/lib/libQt6PrintSupport.so /opt/qt5/lib/libQt6Widgets.so /opt/qt5/lib/libQt6Gui.so /opt/qt5/lib/libQt6QmlModels.so /opt/qt5/lib/libQt6Qml.so /opt/qt5/lib/libQt6Network.so /opt/qt5/lib/libQt6Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		moc_widget.o
DIST          = /opt/qt5/mkspecs/features/spec_pre.prf \
		/opt/qt5/mkspecs/common/unix.conf \
		/opt/qt5/mkspecs/common/linux.conf \
		/opt/qt5/mkspecs/common/sanitize.conf \
		/opt/qt5/mkspecs/common/gcc-base.conf \
		/opt/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/mkspecs/common/g++-base.conf \
		/opt/qt5/mkspecs/common/g++-unix.conf \
		/opt/qt5/mkspecs/qconfig.pri \
		/opt/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_linuxofono_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/mkspecs/features/qt_functions.prf \
		/opt/qt5/mkspecs/features/qt_config.prf \
		/opt/qt5/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/mkspecs/features/toolchain.prf \
		/opt/qt5/mkspecs/features/default_pre.prf \
		/opt/qt5/mkspecs/features/resolve_config.prf \
		/opt/qt5/mkspecs/features/default_post.prf \
		/opt/qt5/mkspecs/features/warn_on.prf \
		/opt/qt5/mkspecs/features/qt.prf \
		/opt/qt5/mkspecs/features/resources_functions.prf \
		/opt/qt5/mkspecs/features/resources.prf \
		/opt/qt5/mkspecs/features/moc.prf \
		/opt/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qt5/mkspecs/features/uic.prf \
		/opt/qt5/mkspecs/features/unix/thread.prf \
		/opt/qt5/mkspecs/features/qmake_use.prf \
		/opt/qt5/mkspecs/features/file_copies.prf \
		/opt/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qt5/mkspecs/features/exceptions.prf \
		/opt/qt5/mkspecs/features/yacc.prf \
		/opt/qt5/mkspecs/features/lex.prf \
		browser.pro widget.h main.cpp \
		widget.cpp
QMAKE_TARGET  = browser
DESTDIR       = 
TARGET        = browser


first: all
####### Build rules

browser:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: browser.pro /opt/qt5/mkspecs/linux-g++/qmake.conf /opt/qt5/mkspecs/features/spec_pre.prf \
		/opt/qt5/mkspecs/common/unix.conf \
		/opt/qt5/mkspecs/common/linux.conf \
		/opt/qt5/mkspecs/common/sanitize.conf \
		/opt/qt5/mkspecs/common/gcc-base.conf \
		/opt/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/mkspecs/common/g++-base.conf \
		/opt/qt5/mkspecs/common/g++-unix.conf \
		/opt/qt5/mkspecs/qconfig.pri \
		/opt/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_linuxofono_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/mkspecs/features/qt_functions.prf \
		/opt/qt5/mkspecs/features/qt_config.prf \
		/opt/qt5/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/mkspecs/features/toolchain.prf \
		/opt/qt5/mkspecs/features/default_pre.prf \
		/opt/qt5/mkspecs/features/resolve_config.prf \
		/opt/qt5/mkspecs/features/default_post.prf \
		/opt/qt5/mkspecs/features/warn_on.prf \
		/opt/qt5/mkspecs/features/qt.prf \
		/opt/qt5/mkspecs/features/resources_functions.prf \
		/opt/qt5/mkspecs/features/resources.prf \
		/opt/qt5/mkspecs/features/moc.prf \
		/opt/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qt5/mkspecs/features/uic.prf \
		/opt/qt5/mkspecs/features/unix/thread.prf \
		/opt/qt5/mkspecs/features/qmake_use.prf \
		/opt/qt5/mkspecs/features/file_copies.prf \
		/opt/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qt5/mkspecs/features/exceptions.prf \
		/opt/qt5/mkspecs/features/yacc.prf \
		/opt/qt5/mkspecs/features/lex.prf \
		browser.pro
	$(QMAKE) -o Makefile browser.pro
/opt/qt5/mkspecs/features/spec_pre.prf:
/opt/qt5/mkspecs/common/unix.conf:
/opt/qt5/mkspecs/common/linux.conf:
/opt/qt5/mkspecs/common/sanitize.conf:
/opt/qt5/mkspecs/common/gcc-base.conf:
/opt/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/qt5/mkspecs/common/g++-base.conf:
/opt/qt5/mkspecs/common/g++-unix.conf:
/opt/qt5/mkspecs/qconfig.pri:
/opt/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_linuxofono_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/opt/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5/mkspecs/features/qt_functions.prf:
/opt/qt5/mkspecs/features/qt_config.prf:
/opt/qt5/mkspecs/linux-g++/qmake.conf:
/opt/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt5/mkspecs/features/exclusive_builds.prf:
/opt/qt5/mkspecs/features/toolchain.prf:
/opt/qt5/mkspecs/features/default_pre.prf:
/opt/qt5/mkspecs/features/resolve_config.prf:
/opt/qt5/mkspecs/features/default_post.prf:
/opt/qt5/mkspecs/features/warn_on.prf:
/opt/qt5/mkspecs/features/qt.prf:
/opt/qt5/mkspecs/features/resources_functions.prf:
/opt/qt5/mkspecs/features/resources.prf:
/opt/qt5/mkspecs/features/moc.prf:
/opt/qt5/mkspecs/features/unix/opengl.prf:
/opt/qt5/mkspecs/features/uic.prf:
/opt/qt5/mkspecs/features/unix/thread.prf:
/opt/qt5/mkspecs/features/qmake_use.prf:
/opt/qt5/mkspecs/features/file_copies.prf:
/opt/qt5/mkspecs/features/testcase_targets.prf:
/opt/qt5/mkspecs/features/exceptions.prf:
/opt/qt5/mkspecs/features/yacc.prf:
/opt/qt5/mkspecs/features/lex.prf:
browser.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile browser.pro

qmake_all: FORCE


all: Makefile browser

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /opt/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: widget.h \
		/opt/qt5/include/QtWidgets/QWidget \
		/opt/qt5/include/QtWidgets/qwidget.h \
		/opt/qt5/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5/include/QtGui/qtguiglobal.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtGui/qtgui-config.h \
		/opt/qt5/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5/include/QtGui/qwindowdefs.h \
		/opt/qt5/include/QtCore/qobjectdefs.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qtmetamacros.h \
		/opt/qt5/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/include/QtCore/qcontainerfwd.h \
		/opt/qt5/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/include/QtCore/qobject.h \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qpair.h \
		/opt/qt5/include/QtCore/qarraydatapointer.h \
		/opt/qt5/include/QtCore/qarraydataops.h \
		/opt/qt5/include/QtCore/qcontainertools_impl.h \
		/opt/qt5/include/QtCore/qstringliteral.h \
		/opt/qt5/include/QtCore/qstringalgorithms.h \
		/opt/qt5/include/QtCore/qstringview.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		/opt/qt5/include/QtCore/qlist.h \
		/opt/qt5/include/QtCore/qvector.h \
		/opt/qt5/include/QtCore/qhashfunctions.h \
		/opt/qt5/include/QtCore/qiterator.h \
		/opt/qt5/include/QtCore/qpoint.h \
		/opt/qt5/include/QtCore/qbytearraylist.h \
		/opt/qt5/include/QtCore/qstringlist.h \
		/opt/qt5/include/QtCore/qalgorithms.h \
		/opt/qt5/include/QtCore/qregexp.h \
		/opt/qt5/include/QtCore/qstringmatcher.h \
		/opt/qt5/include/QtCore/qcoreevent.h \
		/opt/qt5/include/QtCore/qscopedpointer.h \
		/opt/qt5/include/QtCore/qmetatype.h \
		/opt/qt5/include/QtCore/qvarlengtharray.h \
		/opt/qt5/include/QtCore/qobject_impl.h \
		/opt/qt5/include/QtCore/qmargins.h \
		/opt/qt5/include/QtGui/qpaintdevice.h \
		/opt/qt5/include/QtCore/qrect.h \
		/opt/qt5/include/QtCore/qsize.h \
		/opt/qt5/include/QtGui/qpalette.h \
		/opt/qt5/include/QtGui/qcolor.h \
		/opt/qt5/include/QtGui/qrgb.h \
		/opt/qt5/include/QtGui/qrgba64.h \
		/opt/qt5/include/QtGui/qbrush.h \
		/opt/qt5/include/QtGui/qmatrix.h \
		/opt/qt5/include/QtGui/qpolygon.h \
		/opt/qt5/include/QtGui/qregion.h \
		/opt/qt5/include/QtCore/qdatastream.h \
		/opt/qt5/include/QtCore/qiodevice.h \
		/opt/qt5/include/QtCore/qline.h \
		/opt/qt5/include/QtGui/qtransform.h \
		/opt/qt5/include/QtGui/qpainterpath.h \
		/opt/qt5/include/QtGui/qimage.h \
		/opt/qt5/include/QtGui/qpixelformat.h \
		/opt/qt5/include/QtGui/qpixmap.h \
		/opt/qt5/include/QtCore/qsharedpointer.h \
		/opt/qt5/include/QtCore/qshareddata.h \
		/opt/qt5/include/QtCore/qhash.h \
		/opt/qt5/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/include/QtGui/qfont.h \
		/opt/qt5/include/QtGui/qfontmetrics.h \
		/opt/qt5/include/QtGui/qfontinfo.h \
		/opt/qt5/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/include/QtGui/qcursor.h \
		/opt/qt5/include/QtGui/qkeysequence.h \
		/opt/qt5/include/QtGui/qevent.h \
		/opt/qt5/include/QtCore/qvariant.h \
		/opt/qt5/include/QtCore/qmap.h \
		/opt/qt5/include/QtCore/qdebug.h \
		/opt/qt5/include/QtCore/qtextstream.h \
		/opt/qt5/include/QtCore/qlocale.h \
		/opt/qt5/include/QtCore/qset.h \
		/opt/qt5/include/QtCore/qcontiguouscache.h \
		/opt/qt5/include/QtCore/qurl.h \
		/opt/qt5/include/QtCore/qurlquery.h \
		/opt/qt5/include/QtCore/qfile.h \
		/opt/qt5/include/QtCore/qfiledevice.h \
		/opt/qt5/include/QtGui/qvector2d.h \
		/opt/qt5/include/QtGui/qtouchdevice.h \
		/opt/qt5/include/QtWebEngineWidgets/QWebEngineView \
		/opt/qt5/include/QtWebEngineWidgets/qwebengineview.h \
		/opt/qt5/include/QtGui/qpainter.h \
		/opt/qt5/include/QtGui/qtextoption.h \
		/opt/qt5/include/QtGui/qpen.h \
		/opt/qt5/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/qt5/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt5/include/QtNetwork/qtnetwork-config.h \
		/opt/qt5/include/QtNetwork/qnetworkrequest.h \
		/opt/qt5/include/QtCore/QSharedDataPointer \
		/opt/qt5/include/QtCore/QString \
		/opt/qt5/include/QtCore/QUrl \
		/opt/qt5/include/QtCore/QVariant \
		/opt/qt5/include/QtCore/QVector \
		/opt/qt5/include/QtCore/QObject \
		/opt/qt5/include/QtNetwork/QSslConfiguration \
		/opt/qt5/include/QtNetwork/qsslconfiguration.h \
		/opt/qt5/include/QtNetwork/qsslsocket.h \
		/opt/qt5/include/QtNetwork/qtcpsocket.h \
		/opt/qt5/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/include/QtNetwork/qsslerror.h \
		/opt/qt5/include/QtNetwork/qsslcertificate.h \
		/opt/qt5/include/QtCore/qcryptographichash.h \
		/opt/qt5/include/QtCore/qdatetime.h \
		/opt/qt5/include/QtNetwork/qssl.h \
		/opt/qt5/include/QtCore/QFlags \
		/opt/qt5/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/qt5/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/qt5/include/QtCore/QMetaType \
		/opt/qt5/include/QtWebEngineWidgets/qtwebenginewidgetsglobal.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebenginepage.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebengineclientcertificateselection.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebenginedownloaditem.h \
		/opt/qt5/include/QtWebEngineCore/qwebenginecallback.h \
		/opt/qt5/include/QtWebEngineCore/qtwebenginecoreglobal.h \
		/opt/qt5/include/QtWebEngineCore/qtwebenginecore-config.h \
		/opt/qt5/include/QtWebEngineCore/qwebenginehttprequest.h \
		/opt/qt5/include/QtGui/qpagelayout.h \
		/opt/qt5/include/QtGui/qpagesize.h \
		/opt/qt5/include/QtWidgets/QLineEdit \
		/opt/qt5/include/QtWidgets/qlineedit.h \
		/opt/qt5/include/QtWidgets/qframe.h \
		/opt/qt5/include/QtGui/qtextcursor.h \
		/opt/qt5/include/QtGui/qtextformat.h \
		/opt/qt5/include/QtWidgets/QPushButton \
		/opt/qt5/include/QtWidgets/qpushbutton.h \
		/opt/qt5/include/QtWidgets/qabstractbutton.h \
		/opt/qt5/include/QtGui/qicon.h \
		/opt/qt5/include/QtWidgets/QGridLayout \
		/opt/qt5/include/QtWidgets/qgridlayout.h \
		/opt/qt5/include/QtWidgets/qlayout.h \
		/opt/qt5/include/QtWidgets/qlayoutitem.h \
		/opt/qt5/include/QtWidgets/qboxlayout.h \
		/opt/qt5/include/QtCore/QFile \
		/opt/qt5/include/QtCore/QTextStream \
		/opt/qt5/include/QtWidgets/QMenuBar \
		/opt/qt5/include/QtWidgets/qmenubar.h \
		/opt/qt5/include/QtWidgets/qmenu.h \
		/opt/qt5/include/QtWidgets/qaction.h \
		/opt/qt5/include/QtGui/qguiaction.h \
		/opt/qt5/include/QtWidgets/qactiongroup.h \
		/opt/qt5/include/QtGui/qguiactiongroup.h \
		/opt/qt5/include/QtWidgets/QAction \
		/opt/qt5/include/QtWidgets/QTabWidget \
		/opt/qt5/include/QtWidgets/qtabwidget.h \
		moc_predefs.h \
		/opt/qt5/bin/moc
	/opt/qt5/bin/moc $(DEFINES) --include /media/sda3/root/c/browser/moc_predefs.h -I/opt/qt5/mkspecs/linux-g++ -I/media/sda3/root/c/browser -I/media/sda3/root/c/browser -I/opt/qt5/include -I/opt/qt5/include/QtWebEngineWidgets -I/opt/qt5/include/QtWebEngineCore -I/opt/qt5/include/QtQuick -I/opt/qt5/include/QtPrintSupport -I/opt/qt5/include/QtWidgets -I/opt/qt5/include/QtGui -I/opt/qt5/include/QtQmlModels -I/opt/qt5/include/QtQml -I/opt/qt5/include/QtNetwork -I/opt/qt5/include/QtCore -I/usr/include/c++/6.3.0 -I/usr/include/c++/6.3.0/x86_64-pc-linux-gnu -I/usr/include/c++/6.3.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/include-fixed -I/usr/include widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp widget.h \
		/opt/qt5/include/QtWidgets/QWidget \
		/opt/qt5/include/QtWidgets/qwidget.h \
		/opt/qt5/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5/include/QtGui/qtguiglobal.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtGui/qtgui-config.h \
		/opt/qt5/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5/include/QtGui/qwindowdefs.h \
		/opt/qt5/include/QtCore/qobjectdefs.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qtmetamacros.h \
		/opt/qt5/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/include/QtCore/qcontainerfwd.h \
		/opt/qt5/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/include/QtCore/qobject.h \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qpair.h \
		/opt/qt5/include/QtCore/qarraydatapointer.h \
		/opt/qt5/include/QtCore/qarraydataops.h \
		/opt/qt5/include/QtCore/qcontainertools_impl.h \
		/opt/qt5/include/QtCore/qstringliteral.h \
		/opt/qt5/include/QtCore/qstringalgorithms.h \
		/opt/qt5/include/QtCore/qstringview.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		/opt/qt5/include/QtCore/qlist.h \
		/opt/qt5/include/QtCore/qvector.h \
		/opt/qt5/include/QtCore/qhashfunctions.h \
		/opt/qt5/include/QtCore/qiterator.h \
		/opt/qt5/include/QtCore/qpoint.h \
		/opt/qt5/include/QtCore/qbytearraylist.h \
		/opt/qt5/include/QtCore/qstringlist.h \
		/opt/qt5/include/QtCore/qalgorithms.h \
		/opt/qt5/include/QtCore/qregexp.h \
		/opt/qt5/include/QtCore/qstringmatcher.h \
		/opt/qt5/include/QtCore/qcoreevent.h \
		/opt/qt5/include/QtCore/qscopedpointer.h \
		/opt/qt5/include/QtCore/qmetatype.h \
		/opt/qt5/include/QtCore/qvarlengtharray.h \
		/opt/qt5/include/QtCore/qobject_impl.h \
		/opt/qt5/include/QtCore/qmargins.h \
		/opt/qt5/include/QtGui/qpaintdevice.h \
		/opt/qt5/include/QtCore/qrect.h \
		/opt/qt5/include/QtCore/qsize.h \
		/opt/qt5/include/QtGui/qpalette.h \
		/opt/qt5/include/QtGui/qcolor.h \
		/opt/qt5/include/QtGui/qrgb.h \
		/opt/qt5/include/QtGui/qrgba64.h \
		/opt/qt5/include/QtGui/qbrush.h \
		/opt/qt5/include/QtGui/qmatrix.h \
		/opt/qt5/include/QtGui/qpolygon.h \
		/opt/qt5/include/QtGui/qregion.h \
		/opt/qt5/include/QtCore/qdatastream.h \
		/opt/qt5/include/QtCore/qiodevice.h \
		/opt/qt5/include/QtCore/qline.h \
		/opt/qt5/include/QtGui/qtransform.h \
		/opt/qt5/include/QtGui/qpainterpath.h \
		/opt/qt5/include/QtGui/qimage.h \
		/opt/qt5/include/QtGui/qpixelformat.h \
		/opt/qt5/include/QtGui/qpixmap.h \
		/opt/qt5/include/QtCore/qsharedpointer.h \
		/opt/qt5/include/QtCore/qshareddata.h \
		/opt/qt5/include/QtCore/qhash.h \
		/opt/qt5/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/include/QtGui/qfont.h \
		/opt/qt5/include/QtGui/qfontmetrics.h \
		/opt/qt5/include/QtGui/qfontinfo.h \
		/opt/qt5/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/include/QtGui/qcursor.h \
		/opt/qt5/include/QtGui/qkeysequence.h \
		/opt/qt5/include/QtGui/qevent.h \
		/opt/qt5/include/QtCore/qvariant.h \
		/opt/qt5/include/QtCore/qmap.h \
		/opt/qt5/include/QtCore/qdebug.h \
		/opt/qt5/include/QtCore/qtextstream.h \
		/opt/qt5/include/QtCore/qlocale.h \
		/opt/qt5/include/QtCore/qset.h \
		/opt/qt5/include/QtCore/qcontiguouscache.h \
		/opt/qt5/include/QtCore/qurl.h \
		/opt/qt5/include/QtCore/qurlquery.h \
		/opt/qt5/include/QtCore/qfile.h \
		/opt/qt5/include/QtCore/qfiledevice.h \
		/opt/qt5/include/QtGui/qvector2d.h \
		/opt/qt5/include/QtGui/qtouchdevice.h \
		/opt/qt5/include/QtWebEngineWidgets/QWebEngineView \
		/opt/qt5/include/QtWebEngineWidgets/qwebengineview.h \
		/opt/qt5/include/QtGui/qpainter.h \
		/opt/qt5/include/QtGui/qtextoption.h \
		/opt/qt5/include/QtGui/qpen.h \
		/opt/qt5/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/qt5/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt5/include/QtNetwork/qtnetwork-config.h \
		/opt/qt5/include/QtNetwork/qnetworkrequest.h \
		/opt/qt5/include/QtCore/QSharedDataPointer \
		/opt/qt5/include/QtCore/QString \
		/opt/qt5/include/QtCore/QUrl \
		/opt/qt5/include/QtCore/QVariant \
		/opt/qt5/include/QtCore/QVector \
		/opt/qt5/include/QtCore/QObject \
		/opt/qt5/include/QtNetwork/QSslConfiguration \
		/opt/qt5/include/QtNetwork/qsslconfiguration.h \
		/opt/qt5/include/QtNetwork/qsslsocket.h \
		/opt/qt5/include/QtNetwork/qtcpsocket.h \
		/opt/qt5/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/include/QtNetwork/qsslerror.h \
		/opt/qt5/include/QtNetwork/qsslcertificate.h \
		/opt/qt5/include/QtCore/qcryptographichash.h \
		/opt/qt5/include/QtCore/qdatetime.h \
		/opt/qt5/include/QtNetwork/qssl.h \
		/opt/qt5/include/QtCore/QFlags \
		/opt/qt5/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/qt5/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/qt5/include/QtCore/QMetaType \
		/opt/qt5/include/QtWebEngineWidgets/qtwebenginewidgetsglobal.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebenginepage.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebengineclientcertificateselection.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebenginedownloaditem.h \
		/opt/qt5/include/QtWebEngineCore/qwebenginecallback.h \
		/opt/qt5/include/QtWebEngineCore/qtwebenginecoreglobal.h \
		/opt/qt5/include/QtWebEngineCore/qtwebenginecore-config.h \
		/opt/qt5/include/QtWebEngineCore/qwebenginehttprequest.h \
		/opt/qt5/include/QtGui/qpagelayout.h \
		/opt/qt5/include/QtGui/qpagesize.h \
		/opt/qt5/include/QtWidgets/QLineEdit \
		/opt/qt5/include/QtWidgets/qlineedit.h \
		/opt/qt5/include/QtWidgets/qframe.h \
		/opt/qt5/include/QtGui/qtextcursor.h \
		/opt/qt5/include/QtGui/qtextformat.h \
		/opt/qt5/include/QtWidgets/QPushButton \
		/opt/qt5/include/QtWidgets/qpushbutton.h \
		/opt/qt5/include/QtWidgets/qabstractbutton.h \
		/opt/qt5/include/QtGui/qicon.h \
		/opt/qt5/include/QtWidgets/QGridLayout \
		/opt/qt5/include/QtWidgets/qgridlayout.h \
		/opt/qt5/include/QtWidgets/qlayout.h \
		/opt/qt5/include/QtWidgets/qlayoutitem.h \
		/opt/qt5/include/QtWidgets/qboxlayout.h \
		/opt/qt5/include/QtCore/QFile \
		/opt/qt5/include/QtCore/QTextStream \
		/opt/qt5/include/QtWidgets/QMenuBar \
		/opt/qt5/include/QtWidgets/qmenubar.h \
		/opt/qt5/include/QtWidgets/qmenu.h \
		/opt/qt5/include/QtWidgets/qaction.h \
		/opt/qt5/include/QtGui/qguiaction.h \
		/opt/qt5/include/QtWidgets/qactiongroup.h \
		/opt/qt5/include/QtGui/qguiactiongroup.h \
		/opt/qt5/include/QtWidgets/QAction \
		/opt/qt5/include/QtWidgets/QTabWidget \
		/opt/qt5/include/QtWidgets/qtabwidget.h \
		/opt/qt5/include/QtWidgets/QApplication \
		/opt/qt5/include/QtWidgets/qapplication.h \
		/opt/qt5/include/QtCore/qcoreapplication.h \
		/opt/qt5/include/QtCore/qeventloop.h \
		/opt/qt5/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5/include/QtGui/qguiapplication.h \
		/opt/qt5/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		/opt/qt5/include/QtWidgets/QWidget \
		/opt/qt5/include/QtWidgets/qwidget.h \
		/opt/qt5/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5/include/QtGui/qtguiglobal.h \
		/opt/qt5/include/QtCore/qglobal.h \
		/opt/qt5/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5/include/QtCore/qconfig.h \
		/opt/qt5/include/QtCore/qtcore-config.h \
		/opt/qt5/include/QtCore/qsystemdetection.h \
		/opt/qt5/include/QtCore/qprocessordetection.h \
		/opt/qt5/include/QtCore/qcompilerdetection.h \
		/opt/qt5/include/QtCore/qtypeinfo.h \
		/opt/qt5/include/QtCore/qsysinfo.h \
		/opt/qt5/include/QtCore/qlogging.h \
		/opt/qt5/include/QtCore/qflags.h \
		/opt/qt5/include/QtCore/qatomic.h \
		/opt/qt5/include/QtCore/qbasicatomic.h \
		/opt/qt5/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/include/QtCore/qgenericatomic.h \
		/opt/qt5/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/include/QtCore/qatomic_msvc.h \
		/opt/qt5/include/QtCore/qglobalstatic.h \
		/opt/qt5/include/QtCore/qmutex.h \
		/opt/qt5/include/QtCore/qnumeric.h \
		/opt/qt5/include/QtCore/qversiontagging.h \
		/opt/qt5/include/QtGui/qtgui-config.h \
		/opt/qt5/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5/include/QtGui/qwindowdefs.h \
		/opt/qt5/include/QtCore/qobjectdefs.h \
		/opt/qt5/include/QtCore/qnamespace.h \
		/opt/qt5/include/QtCore/qtmetamacros.h \
		/opt/qt5/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/include/QtCore/qcontainerfwd.h \
		/opt/qt5/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/include/QtCore/qobject.h \
		/opt/qt5/include/QtCore/qstring.h \
		/opt/qt5/include/QtCore/qchar.h \
		/opt/qt5/include/QtCore/qbytearray.h \
		/opt/qt5/include/QtCore/qrefcount.h \
		/opt/qt5/include/QtCore/qarraydata.h \
		/opt/qt5/include/QtCore/qpair.h \
		/opt/qt5/include/QtCore/qarraydatapointer.h \
		/opt/qt5/include/QtCore/qarraydataops.h \
		/opt/qt5/include/QtCore/qcontainertools_impl.h \
		/opt/qt5/include/QtCore/qstringliteral.h \
		/opt/qt5/include/QtCore/qstringalgorithms.h \
		/opt/qt5/include/QtCore/qstringview.h \
		/opt/qt5/include/QtCore/qstringbuilder.h \
		/opt/qt5/include/QtCore/qlist.h \
		/opt/qt5/include/QtCore/qvector.h \
		/opt/qt5/include/QtCore/qhashfunctions.h \
		/opt/qt5/include/QtCore/qiterator.h \
		/opt/qt5/include/QtCore/qpoint.h \
		/opt/qt5/include/QtCore/qbytearraylist.h \
		/opt/qt5/include/QtCore/qstringlist.h \
		/opt/qt5/include/QtCore/qalgorithms.h \
		/opt/qt5/include/QtCore/qregexp.h \
		/opt/qt5/include/QtCore/qstringmatcher.h \
		/opt/qt5/include/QtCore/qcoreevent.h \
		/opt/qt5/include/QtCore/qscopedpointer.h \
		/opt/qt5/include/QtCore/qmetatype.h \
		/opt/qt5/include/QtCore/qvarlengtharray.h \
		/opt/qt5/include/QtCore/qobject_impl.h \
		/opt/qt5/include/QtCore/qmargins.h \
		/opt/qt5/include/QtGui/qpaintdevice.h \
		/opt/qt5/include/QtCore/qrect.h \
		/opt/qt5/include/QtCore/qsize.h \
		/opt/qt5/include/QtGui/qpalette.h \
		/opt/qt5/include/QtGui/qcolor.h \
		/opt/qt5/include/QtGui/qrgb.h \
		/opt/qt5/include/QtGui/qrgba64.h \
		/opt/qt5/include/QtGui/qbrush.h \
		/opt/qt5/include/QtGui/qmatrix.h \
		/opt/qt5/include/QtGui/qpolygon.h \
		/opt/qt5/include/QtGui/qregion.h \
		/opt/qt5/include/QtCore/qdatastream.h \
		/opt/qt5/include/QtCore/qiodevice.h \
		/opt/qt5/include/QtCore/qline.h \
		/opt/qt5/include/QtGui/qtransform.h \
		/opt/qt5/include/QtGui/qpainterpath.h \
		/opt/qt5/include/QtGui/qimage.h \
		/opt/qt5/include/QtGui/qpixelformat.h \
		/opt/qt5/include/QtGui/qpixmap.h \
		/opt/qt5/include/QtCore/qsharedpointer.h \
		/opt/qt5/include/QtCore/qshareddata.h \
		/opt/qt5/include/QtCore/qhash.h \
		/opt/qt5/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/include/QtGui/qfont.h \
		/opt/qt5/include/QtGui/qfontmetrics.h \
		/opt/qt5/include/QtGui/qfontinfo.h \
		/opt/qt5/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/include/QtGui/qcursor.h \
		/opt/qt5/include/QtGui/qkeysequence.h \
		/opt/qt5/include/QtGui/qevent.h \
		/opt/qt5/include/QtCore/qvariant.h \
		/opt/qt5/include/QtCore/qmap.h \
		/opt/qt5/include/QtCore/qdebug.h \
		/opt/qt5/include/QtCore/qtextstream.h \
		/opt/qt5/include/QtCore/qlocale.h \
		/opt/qt5/include/QtCore/qset.h \
		/opt/qt5/include/QtCore/qcontiguouscache.h \
		/opt/qt5/include/QtCore/qurl.h \
		/opt/qt5/include/QtCore/qurlquery.h \
		/opt/qt5/include/QtCore/qfile.h \
		/opt/qt5/include/QtCore/qfiledevice.h \
		/opt/qt5/include/QtGui/qvector2d.h \
		/opt/qt5/include/QtGui/qtouchdevice.h \
		/opt/qt5/include/QtWebEngineWidgets/QWebEngineView \
		/opt/qt5/include/QtWebEngineWidgets/qwebengineview.h \
		/opt/qt5/include/QtGui/qpainter.h \
		/opt/qt5/include/QtGui/qtextoption.h \
		/opt/qt5/include/QtGui/qpen.h \
		/opt/qt5/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/qt5/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt5/include/QtNetwork/qtnetwork-config.h \
		/opt/qt5/include/QtNetwork/qnetworkrequest.h \
		/opt/qt5/include/QtCore/QSharedDataPointer \
		/opt/qt5/include/QtCore/QString \
		/opt/qt5/include/QtCore/QUrl \
		/opt/qt5/include/QtCore/QVariant \
		/opt/qt5/include/QtCore/QVector \
		/opt/qt5/include/QtCore/QObject \
		/opt/qt5/include/QtNetwork/QSslConfiguration \
		/opt/qt5/include/QtNetwork/qsslconfiguration.h \
		/opt/qt5/include/QtNetwork/qsslsocket.h \
		/opt/qt5/include/QtNetwork/qtcpsocket.h \
		/opt/qt5/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/include/QtNetwork/qsslerror.h \
		/opt/qt5/include/QtNetwork/qsslcertificate.h \
		/opt/qt5/include/QtCore/qcryptographichash.h \
		/opt/qt5/include/QtCore/qdatetime.h \
		/opt/qt5/include/QtNetwork/qssl.h \
		/opt/qt5/include/QtCore/QFlags \
		/opt/qt5/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/qt5/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/qt5/include/QtCore/QMetaType \
		/opt/qt5/include/QtWebEngineWidgets/qtwebenginewidgetsglobal.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebenginepage.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebengineclientcertificateselection.h \
		/opt/qt5/include/QtWebEngineWidgets/qwebenginedownloaditem.h \
		/opt/qt5/include/QtWebEngineCore/qwebenginecallback.h \
		/opt/qt5/include/QtWebEngineCore/qtwebenginecoreglobal.h \
		/opt/qt5/include/QtWebEngineCore/qtwebenginecore-config.h \
		/opt/qt5/include/QtWebEngineCore/qwebenginehttprequest.h \
		/opt/qt5/include/QtGui/qpagelayout.h \
		/opt/qt5/include/QtGui/qpagesize.h \
		/opt/qt5/include/QtWidgets/QLineEdit \
		/opt/qt5/include/QtWidgets/qlineedit.h \
		/opt/qt5/include/QtWidgets/qframe.h \
		/opt/qt5/include/QtGui/qtextcursor.h \
		/opt/qt5/include/QtGui/qtextformat.h \
		/opt/qt5/include/QtWidgets/QPushButton \
		/opt/qt5/include/QtWidgets/qpushbutton.h \
		/opt/qt5/include/QtWidgets/qabstractbutton.h \
		/opt/qt5/include/QtGui/qicon.h \
		/opt/qt5/include/QtWidgets/QGridLayout \
		/opt/qt5/include/QtWidgets/qgridlayout.h \
		/opt/qt5/include/QtWidgets/qlayout.h \
		/opt/qt5/include/QtWidgets/qlayoutitem.h \
		/opt/qt5/include/QtWidgets/qboxlayout.h \
		/opt/qt5/include/QtCore/QFile \
		/opt/qt5/include/QtCore/QTextStream \
		/opt/qt5/include/QtWidgets/QMenuBar \
		/opt/qt5/include/QtWidgets/qmenubar.h \
		/opt/qt5/include/QtWidgets/qmenu.h \
		/opt/qt5/include/QtWidgets/qaction.h \
		/opt/qt5/include/QtGui/qguiaction.h \
		/opt/qt5/include/QtWidgets/qactiongroup.h \
		/opt/qt5/include/QtGui/qguiactiongroup.h \
		/opt/qt5/include/QtWidgets/QAction \
		/opt/qt5/include/QtWidgets/QTabWidget \
		/opt/qt5/include/QtWidgets/qtabwidget.h \
		/opt/qt5/include/QtCore/QTimer \
		/opt/qt5/include/QtCore/qtimer.h \
		/opt/qt5/include/QtCore/qbasictimer.h \
		/opt/qt5/include/QtWidgets/QToolButton \
		/opt/qt5/include/QtWidgets/qtoolbutton.h \
		/opt/qt5/include/QtWidgets/QLabel \
		/opt/qt5/include/QtWidgets/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

